"""
=====================================================================
 University AI Course Assistant — Retrieval Pipeline
=====================================================================
Supports three interaction modes:
  • ask        — Answer questions with explanations
  • quiz        — Generate quiz questions on a topic
  • summarize   — Summarise a topic

Six knowledge source namespaces:
  qna, image, audio, youtube, documents, handwritten

Pipeline:
  1. Planner Agent (Gemini) → structured QueryPlan via Pydantic
      - mode-aware intent analysis
      - 2-5 diverse sub-queries (Jaccard-deduped)
      - per-source budgets with dense_k, bm25_k, use_mmr, priority_weight
      - per-query source priority hints
      - answer format guidance
  2. Embed all sub-queries in parallel
  3. Fan-out: for each (sub-query × source) pair
      a. Dense ANN retrieval (Pinecone)
      b. BM25 on the dense corpus (rank-bm25)
      c. MMR diversity filter on dense results (when use_mmr=True)
  4. Metadata-boosted RRF fusion across all ranked lists
  5. Return citation-ready RetrievalResult

Install:
    pip install google-genai pinecone rank-bm25 pydantic numpy

Usage:
    from retrieval_pipeline import retrieve, RetrievalMode

    result = retrieve(
        query="What is TCP three-way handshake?",
        course_id="CN301",
        mode=RetrievalMode.ASK,
        top_k=8,
    )
    print(result.to_context_string())
    print(result.to_answer_prompt())
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import re
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Literal, Optional

import numpy as np
from google import genai
from google.genai import types
from pinecone import Pinecone
from pydantic import BaseModel, Field, ValidationInfo, field_validator, model_validator
from rank_bm25 import BM25Okapi

from apps.worker.core.pinecone import get_course_index_name

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# Environment / global config
# ─────────────────────────────────────────────────────────────────────────────

GEMINI_API_KEY      = os.getenv("GEMINI_API_KEY", "")
PINECONE_API_KEY    = os.getenv("PINECONE_API_KEY", "")
PINECONE_INDEX_NAME = os.getenv("PINECONE_INDEX_NAME", "rag-index")
PINECONE_CLOUD      = os.getenv("PINECONE_CLOUD", "aws")
PINECONE_REGION     = os.getenv("PINECONE_ENVIRONMENT", "us-east-1")

EMBEDDING_MODEL = os.getenv("GEMINI_EMBEDDING_MODEL", "gemini-embedding-2")
EMBEDDING_DIM   = int(os.getenv("GEMINI_EMBEDDING_DIM", "1536"))
PLANNER_MODEL   = os.getenv("GEMINI_RETRIEVAL_PLANNER_MODEL", os.getenv("RAG_PLANNER_MODEL", "gemini-2.5-flash"))
PLANNER_FALLBACK_MODEL = os.getenv("GEMINI_RETRIEVAL_FALLBACK_MODEL", "gemini-2.5-flash-lite")

RRF_K = 60
BM25_CORPUS_MULTIPLIER = 3

# ─────────────────────────────────────────────────────────────────────────────
# Interaction modes
# ─────────────────────────────────────────────────────────────────────────────

class RetrievalMode(str, Enum):
    ASK       = "ask"        # Answer questions / explain concepts
    QUIZ      = "quiz"       # Generate quiz questions
    SUMMARIZE = "summarize"  # Summarise a topic


# Source namespaces — must match ingestion pipeline upsert namespaces
SOURCE_NAMESPACES: dict[str, str] = {
    "qna":         os.getenv("QNA_CHUNKING_NAMESPACE", "qna-chunks"),
    "image":       os.getenv("IMAGE_CHUNKING_NAMESPACE", "image-chunks"),
    "audio":       os.getenv("AUDIO_CHUNKING_NAMESPACE", "audio-chunks"),
    "youtube":     os.getenv("YOUTUBE_CHUNKING_NAMESPACE", "youtube-chunks"),
    "documents":   os.getenv("DOCUMENT_CHUNKING_NAMESPACE", "document-chunks"),
    "handwritten": os.getenv("HANDWRITTEN_CHUNKING_NAMESPACE", "handwritten-chunks"),
}
SourceKey = Literal["qna", "image", "audio", "youtube", "documents", "handwritten"]

# ─────────────────────────────────────────────────────────────────────────────
# Pydantic schemas for Planner structured output
# ─────────────────────────────────────────────────────────────────────────────

class SubQuery(BaseModel):
    """One semantically distinct sub-query generated by the planner."""
    text: str = Field(
        ...,
        description=(
            "The sub-query text. Must be self-contained and meaningfully "
            "different from other sub-queries — NOT a paraphrase."
        ),
    )
    facet: str = Field(
        ...,
        description=(
            "What aspect of the original query this targets. Examples: "
            "'definition', 'mechanism', 'worked_example', 'time_complexity', "
            "'exam_phrasing', 'visual_explanation', 'comparison', 'application'."
        ),
    )
    preferred_sources: list[str] = Field(
        ...,
        description=(
            "Ordered list of source keys most likely to have results for THIS "
            "sub-query. Subset of: qna, image, audio, youtube, documents, handwritten."
        ),
    )


class SourceBudget(BaseModel):
    """Retrieval configuration for one knowledge source."""
    source_key: str = Field(..., description="One of: qna, image, audio, youtube, documents, handwritten")
    dense_k: int    = Field(..., ge=2, le=20, description="Dense ANN results to fetch per sub-query.")
    bm25_k: int     = Field(default=0, ge=0, le=12, description="BM25 results to keep per sub-query. 0=disabled.")
    use_mmr: bool   = Field(..., description="Apply MMR diversity filter on dense results.")
    mmr_k: int      = Field(default=5, ge=1, le=15, description="Chunks to keep after MMR. Ignored if use_mmr=False.")
    mmr_lambda: float = Field(default=0.6, ge=0.3, le=0.9, description="MMR trade-off: 1.0=pure relevance, 0.0=pure diversity.")
    priority_weight: float = Field(..., ge=0.2, le=3.0, description="Influence on final RRF fusion score.")

    @field_validator("source_key")
    @classmethod
    def validate_source_key(cls, v: str) -> str:
        valid = set(SOURCE_NAMESPACES.keys())
        if v not in valid:
            raise ValueError(f"source_key must be one of {valid}, got {v!r}")
        return v

    @model_validator(mode="after")
    def mmr_k_le_dense_k(self) -> "SourceBudget":
        if self.use_mmr and self.mmr_k > self.dense_k:
            self.mmr_k = self.dense_k
        return self


class QuizConfig(BaseModel):
    """Configuration specific to quiz generation mode."""
    question_types: list[str] = Field(
        default_factory=lambda: ["mcq", "short_answer", "fill_in_blank"],
        description="Types of questions to generate: mcq, short_answer, fill_in_blank, true_false, numerical.",
    )
    difficulty_distribution: dict[str, float] = Field(
        default_factory=lambda: {"easy": 0.3, "medium": 0.5, "hard": 0.2},
        description="Fraction of questions per difficulty level. Must sum to 1.0.",
    )
    num_questions: int = Field(default=5, ge=1, le=20, description="Number of quiz questions to generate.")
    include_answer_key: bool = Field(default=True, description="Include answer key and explanations.")
    focus_on_exam_patterns: bool = Field(
        default=True,
        description="If True, prioritise qna source heavily to match known exam patterns.",
    )


class SummaryConfig(BaseModel):
    """Configuration specific to summarise mode."""
    depth: Literal["brief", "standard", "deep"] = Field(
        default="standard",
        description="Brief=1 paragraph, Standard=structured with key points, Deep=comprehensive with examples.",
    )
    include_key_terms: bool = Field(default=True, description="Include a glossary of key terms.")
    include_examples: bool = Field(default=True, description="Include worked examples from source material.")
    format: Literal["prose", "bullet_points", "structured_headers"] = Field(
        default="structured_headers",
        description="Output format for the summary.",
    )


class QueryPlan(BaseModel):
    """Complete retrieval plan produced by the Planner Agent."""

    # ── Intent ───────────────────────────────────────────────────────────────
    query_intent: str = Field(..., description="What the student is really asking for, in one sentence.")
    query_category: Literal[
        "theoretical_explanation",
        "definition_or_concept",
        "problem_or_derivation",
        "comparison",
        "worked_example",
        "exam_question",
        "visual_or_diagram",
        "procedural_steps",
        "application",
        "topic_overview",
        "clarification",
    ] = Field(..., description="Primary category of the query.")
    key_concepts: list[str] = Field(..., min_length=2, max_length=10, description="Core concepts central to this query.")
    complexity_level: Literal["basic", "intermediate", "advanced"] = Field(
        ...,
        description="basic=2 sub-queries, intermediate=3-4, advanced=4-5.",
    )

    # ── Sub-queries ──────────────────────────────────────────────────────────
    sub_queries: list[SubQuery] = Field(
        ..., min_length=1, max_length=5,
        description=(
            "2-5 semantically diverse sub-queries targeting different facets. "
            "NEVER paraphrase — each must retrieve different content. "
            "Always include: one exam/textbook phrasing AND one conversational explanation phrasing."
        ),
    )

    # ── Per-source retrieval config ──────────────────────────────────────────
    source_budgets: list[SourceBudget] = Field(
        ..., min_length=1, max_length=6,
        description=(
            "Retrieval configuration for each relevant source. "
            "Include only sources genuinely likely to have relevant content."
        ),
    )

    # ── Mode-specific configs ────────────────────────────────────────────────
    quiz_config: Optional[QuizConfig] = Field(
        default=None,
        description="Populated only when mode=quiz.",
    )
    summary_config: Optional[SummaryConfig] = Field(
        default=None,
        description="Populated only when mode=summarize.",
    )

    # ── Answer generation hints ──────────────────────────────────────────────
    expected_answer_format: Literal[
        "structured_explanation",
        "definition_then_example",
        "comparison_table",
        "worked_solution",
        "conceptual_prose",
        "quiz_questions",
        "topic_summary",
        "bullet_summary",
    ] = Field(..., description="Recommended format for the final answer.")
    expected_answer_length: Literal["short", "medium", "long"] = Field(
        ..., description="short=1-2 paragraphs, medium=3-5 paragraphs, long=full structured."
    )
    domain_keywords: list[str] = Field(
        ..., min_length=1, max_length=15,
        description="Keywords that SHOULD appear in a good answer — used for quality validation.",
    )

    # ── High-value signals for scoring ───────────────────────────────────────
    high_value_signals: list[str] = Field(
        ...,
        description=(
            "Content signals that make a chunk MORE valuable. "
            "E.g. ['contains definition', 'has worked example', 'mentions marks/exam year', "
            "'contains pseudocode', 'shows step-by-step']."
        ),
    )
    low_value_signals: list[str] = Field(
        ...,
        description=(
            "Content signals that make a chunk LESS valuable. "
            "E.g. ['administrative content', 'unrelated subtopic', 'only tangential mention']."
        ),
    )

    @field_validator("key_concepts", "domain_keywords", "sub_queries", "source_budgets", mode="before")
    @classmethod
    def trim_overlong_planner_lists(cls, value, info: ValidationInfo):
        if not isinstance(value, list):
            return value
        limits = {
            "key_concepts": 10,
            "domain_keywords": 15,
            "sub_queries": 5,
            "source_budgets": 6,
        }
        limit = limits.get(info.field_name)
        if limit is None:
            return value
        return value[:limit]


# ─────────────────────────────────────────────────────────────────────────────
# Retrieved chunk output schema
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class RetrievedChunk:
    """One retrieved chunk, citation-ready."""
    chunk_id:          str
    source_key:        str
    namespace:         str
    score:             float           # final combined score
    rrf_score:         float
    retrieval_methods: list[str]

    # Content
    text:              str = ""
    questions:         list[str] = field(default_factory=list)
    answers:           list[str] = field(default_factory=list)

    # Universal provenance
    source_file:       str = ""
    course_id:         str = ""
    page_range:        str = ""
    section_title:     str = ""
    topic:             str = ""
    chunk_type:        str = ""
    keywords:          list[str] = field(default_factory=list)

    # QnA-specific
    year_hint:         Optional[int] = None
    marks_hint:        Optional[int] = None
    difficulty:        str = ""

    # Image-specific
    image_type:        str = ""
    image_summary:     str = ""
    ocr_confidence:    float = 0.0

    # Audio-specific
    strategy:          str = ""
    start_seconds:     float = 0.0
    end_seconds:       float = 0.0
    start_label:       str = ""
    end_label:         str = ""
    lecture_title:     str = ""
    professor:         str = ""
    week_number:       Optional[int] = None

    # YouTube-specific
    video_id:          str = ""
    video_title:       str = ""
    channel_author:    str = ""
    deep_link:         str = ""
    chapter_title:     str = ""

    # Handwritten-specific
    ink_quality:       str = ""
    writing_style:     str = ""
    content_type:      str = ""
    has_equations:     bool = False
    has_diagrams:      bool = False
    model_used:        str = ""

    # Documents-specific
    has_table:         bool = False
    has_image:         bool = False
    has_list:          bool = False

    @property
    def citation_label(self) -> str:
        if self.source_key == "qna":
            parts = [self.source_file or "Q&A Sheet"]
            if self.page_range:
                parts.append(f"pp. {self.page_range}")
            if self.year_hint:
                parts.append(str(self.year_hint))
            if self.marks_hint and self.marks_hint > 0:
                parts.append(f"[{self.marks_hint} marks]")
            return " · ".join(parts)

        elif self.source_key == "image":
            parts = [self.source_file or "Scanned Material"]
            if self.page_range:
                parts.append(f"pp. {self.page_range}")
            if self.image_type:
                parts.append(self.image_type.replace("_", " ").title())
            return " · ".join(parts)

        elif self.source_key == "audio":
            parts = [self.lecture_title or self.source_file or "Lecture"]
            if self.start_label:
                parts.append(f"@ {self.start_label}–{self.end_label}")
            if self.professor:
                parts.append(self.professor)
            if self.week_number:
                parts.append(f"Week {self.week_number}")
            return " · ".join(parts)

        elif self.source_key == "youtube":
            parts = [self.video_title or "YouTube Lecture"]
            if self.start_label:
                parts.append(f"@ {self.start_label}")
            if self.chapter_title and self.chapter_title not in ("Unknown", ""):
                parts.append(self.chapter_title)
            return " · ".join(parts)

        elif self.source_key == "documents":
            parts = [self.source_file or "Course Document"]
            if self.page_range:
                parts.append(f"pp. {self.page_range}")
            if self.section_title:
                parts.append(f"§ {self.section_title}")
            return " · ".join(parts)

        elif self.source_key == "handwritten":
            parts = [self.source_file or "Handwritten Notes"]
            if self.page_range:
                parts.append(f"p. {self.page_range}")
            if self.topic:
                parts.append(self.topic)
            return " · ".join(parts)

        return self.source_file or self.source_key

    @property
    def display_text(self) -> str:
        if self.source_key == "qna" and (self.questions or self.answers):
            parts = [f"Q{i+1}: {q}" for i, q in enumerate(self.questions)]
            parts += [f"A{i+1}: {a}" for i, a in enumerate(self.answers)]
            return "\n".join(parts) if parts else self.text

        elif self.source_key == "audio" and self.start_label:
            return f"[Lecture @ {self.start_label}–{self.end_label}]\n{self.text}"

        elif self.source_key == "youtube" and self.deep_link:
            return f"[YouTube @ {self.start_label} — {self.deep_link}]\n{self.text}"

        elif self.source_key == "image" and self.image_summary:
            return f"[Image: {self.image_type}]\nSummary: {self.image_summary}\n\nExtracted text:\n{self.text}"

        elif self.source_key == "handwritten":
            prefix = "[has equations] " if self.has_equations else ""
            return f"{prefix}{self.text}"

        return self.text

    def to_dict(self) -> dict:
        return {
            "chunk_id":          self.chunk_id,
            "source_key":        self.source_key,
            "score":             round(self.score, 4),
            "rrf_score":         round(self.rrf_score, 4),
            "retrieval_methods": self.retrieval_methods,
            "citation_label":    self.citation_label,
            "display_text":      self.display_text[:800],
            "source_file":       self.source_file,
            "course_id":         self.course_id,
            "page_range":        self.page_range,
            "section_title":     self.section_title,
            "topic":             self.topic,
            "chunk_type":        self.chunk_type,
            "keywords":          self.keywords,
            "year_hint":         self.year_hint,
            "marks_hint":        self.marks_hint,
            "image_type":        self.image_type,
            "image_summary":     self.image_summary[:300] if self.image_summary else "",
            "start_label":       self.start_label,
            "lecture_title":     self.lecture_title,
            "professor":         self.professor,
            "video_title":       self.video_title,
            "deep_link":         self.deep_link,
            "chapter_title":     self.chapter_title,
            "has_equations":     self.has_equations,
            "has_diagrams":      self.has_diagrams,
            "has_table":         self.has_table,
        }


@dataclass
class RetrievalResult:
    """Top-level result returned to the caller."""
    query:            str
    mode:             RetrievalMode
    plan:             QueryPlan
    chunks:           list[RetrievedChunk]
    total_candidates: int
    latency_ms:       float
    source_breakdown: dict[str, int] = field(default_factory=dict)

    def to_context_string(self, max_chunks: Optional[int] = None) -> str:
        selected = self.chunks[:max_chunks] if max_chunks else self.chunks
        parts: list[str] = []
        for i, chunk in enumerate(selected, 1):
            header = (
                f"[{i}] {chunk.source_key.upper()} SOURCE\n"
                f"     Citation : {chunk.citation_label}\n"
                f"     Type     : {chunk.chunk_type or '—'}\n"
                f"     Score    : {chunk.score:.3f}\n"
                f"     Methods  : {', '.join(chunk.retrieval_methods)}"
            )
            parts.append(f"{header}\n\n{chunk.display_text.strip()}")
        divider = "\n" + "─" * 65 + "\n"
        return "\n" + divider.join(parts)

    def to_answer_prompt(self, system_instruction: str = "") -> str:
        plan = self.plan
        mode_instructions = {
            RetrievalMode.ASK: (
                "Answer the student's question clearly and completely, citing every "
                "factual claim with [N] where N is the source number."
            ),
            RetrievalMode.QUIZ: (
                f"Generate {plan.quiz_config.num_questions if plan.quiz_config else 5} "
                "quiz questions based on the retrieved content. "
                "Include answer keys and brief explanations. "
                "Cite source material with [N] notation."
            ),
            RetrievalMode.SUMMARIZE: (
                "Write a comprehensive summary of the topic using the retrieved content. "
                "Cite sources with [N] notation. Cover all key concepts found."
            ),
        }
        default_sys = (
            "You are a knowledgeable university course assistant. "
            + mode_instructions.get(self.mode, mode_instructions[RetrievalMode.ASK])
        )
        sys_text = system_instruction or default_sys
        prompt = (
            f"MODE: {self.mode.value.upper()}\n"
            f"STUDENT QUERY: {self.query}\n\n"
            f"QUERY CATEGORY: {plan.query_category}\n"
            f"ANSWER FORMAT: {plan.expected_answer_format}\n"
            f"ANSWER LENGTH: {plan.expected_answer_length}\n"
            f"KEY CONCEPTS: {', '.join(plan.key_concepts)}\n\n"
        )
        if self.mode == RetrievalMode.QUIZ and plan.quiz_config:
            qc = plan.quiz_config
            prompt += (
                f"QUIZ CONFIG:\n"
                f"  Types: {', '.join(qc.question_types)}\n"
                f"  Count: {qc.num_questions}\n"
                f"  Difficulty: {qc.difficulty_distribution}\n"
                f"  Include answer key: {qc.include_answer_key}\n\n"
            )
        if self.mode == RetrievalMode.SUMMARIZE and plan.summary_config:
            sc = plan.summary_config
            prompt += (
                f"SUMMARY CONFIG:\n"
                f"  Depth: {sc.depth}\n"
                f"  Format: {sc.format}\n"
                f"  Include key terms: {sc.include_key_terms}\n"
                f"  Include examples: {sc.include_examples}\n\n"
            )
        prompt += (
            f"RETRIEVED CONTEXT ({len(self.chunks)} sources):\n"
            f"{self.to_context_string()}\n\n"
            "Now write your response. Every factual claim MUST cite a source [N]."
        )
        return f"{sys_text}\n\n{prompt}"


# ─────────────────────────────────────────────────────────────────────────────
# Planner prompts per mode
# ─────────────────────────────────────────────────────────────────────────────

_SOURCE_GUIDE = """\
═══════════════════════════════════════════════════════════
KNOWLEDGE SOURCES (choose only relevant ones):
═══════════════════════════════════════════════════════════

1. qna — Past-year exam Q&As, mark schemes, theoretical passages from exam PDFs.
   Metadata available: chunk_type (single_qa|multi_qa|passage), year_hint, marks_hint,
   difficulty_hint, has_sub_parts, topic_cluster, topic_label.
   BM25: YES (question numbers, year, marks, exact keywords are critical).
   MMR: NO (each Q&A unit is unique — do not filter them).
   Best for: Exam questions, definitions, theory questions, worked solutions.

2. image — Scanned PDFs, printed lecture slides, lab sheets with OCR+Gemini vision.
   Metadata available: image_type, gemini_summary, gemini_topic, gemini_keywords,
   ocr_confidence, preprocessing_stages, skew_corrected, has_code, has_formula, has_list.
   BM25: YES (OCR text contains technical terms).
   MMR: YES (adjacent pages from same document can be very similar).
   Best for: Diagrams, circuit diagrams, architecture diagrams, visual concepts.

3. audio — Professor lecture recordings (45-90 min), chunked 3 ways:
   sliding_window (backbone), concept_block (topic-aligned), lecture_summary (macro).
   Metadata available: strategy, start_seconds, end_seconds, start_label, end_label,
   lecture_title, professor, week_number, concepts, concept_label, avg_confidence.
   BM25: LIGHT (conversational, keywords less precise).
   MMR: YES (lectures repeat concepts across windows — diversity is important).
   Best for: Intuitive explanations, "why" questions, professor's words on a topic.

4. youtube — YouTube educational video transcripts, chapter-aware chunks.
   Metadata available: video_title, author, chapter_title, chapter_index,
   start_label, end_label, deep_link, concept_tags, topic, summary,
   is_generated_transcript, transcript_language.
   BM25: NO (conversational, unreliable keywords).
   MMR: YES (transcripts repeat constantly).
   Best for: Alternative explanations, step-by-step visual walkthroughs.

5. documents — Digital PDFs, PPTs, DOCX — textbooks, slides, course readings.
   Metadata available: section_title, element_types, has_table, has_image, has_list,
   table_count, image_count, page_start, page_end, chunk_index, total_chunks.
   BM25: YES (structured text with technical terms).
   MMR: YES (slides repeat content across sections).
   Best for: Formal definitions, proofs, textbook-style structured content.

6. handwritten — Handwritten notes (professor + student), OCR'd via Gemini Flash/Pro.
   Metadata available: topic, content_type (notes|diagram|equation|table|mixed),
   has_diagrams, has_equations, has_tables, ink_quality, writing_style, model_used,
   confidence, summary, course_id, course_name, subject, instructor, semester.
   BM25: LIGHT (OCR quality varies; use when keywords are confident).
   MMR: NO (handwritten chunks are already short and distinct).
   Best for: Worked examples, professor's board notes, equations, memory aids.

═══════════════════════════════════════════════════════════
PRIORITY WEIGHT GUIDE for RRF fusion (mode-sensitive):
═══════════════════════════════════════════════════════════
ASK mode (explanation/understanding):
  documents=2.2, qna=2.0, audio=1.8, handwritten=1.3, image=1.2, youtube=1.0

QUIZ mode (exam-focused):
  qna=2.8, documents=1.8, handwritten=1.5, image=1.3, audio=1.0, youtube=0.8

SUMMARIZE mode (broad coverage):
  documents=2.2, audio=2.0, youtube=1.8, qna=1.5, handwritten=1.3, image=1.2

Additional adjustments by query category:
  visual_or_diagram     → image *= 1.5, youtube *= 1.2
  problem_or_derivation → qna *= 1.3, handwritten *= 1.4
  worked_example        → handwritten *= 1.5, qna *= 1.3, audio *= 1.2
  comparison            → documents *= 1.3, youtube *= 1.2
  procedural_steps      → audio *= 1.3, youtube *= 1.3

═══════════════════════════════════════════════════════════
DENSE_K GUIDE (per sub-query, per source):
═══════════════════════════════════════════════════════════
  qna:         4-8  (precise; high signal density)
  image:       3-6  (each image chunk is a full page; don't over-fetch)
  audio:       6-12 (lectures are verbose; need more candidates)
  youtube:     5-8  (similar to audio but more structured)
  documents:   5-9  (slides/textbooks have moderate density)
  handwritten: 3-6  (notes are short; don't over-fetch)

For QUIZ mode: increase qna dense_k by 50% (need more question variety).
For SUMMARIZE mode: increase all dense_k by 20% (need broader coverage).
For BASIC complexity: use lower end of ranges. For ADVANCED: use upper end.
"""

_PLANNER_SYSTEM = (
    """\
You are an expert retrieval planner for a university AI course assistant.
A student has submitted a query. Your job is to produce a complete retrieval plan.

"""
    + _SOURCE_GUIDE
    + """
═══════════════════════════════════════════════════════════
SUB-QUERY DESIGN RULES:
═══════════════════════════════════════════════════════════
• Generate 2-5 sub-queries, each targeting a DIFFERENT facet.
• NEVER paraphrase — each sub-query must retrieve different content.
• Always include one that matches exam/textbook formal phrasing.
• Always include one that matches how a student would ask a professor.
• For algorithms: one for pseudocode/steps + one for time complexity.
• For concepts: one for definition + one for real-world application.
• Set preferred_sources per sub-query — different facets suit different sources.

OUTPUT LIMITS:
Return JSON only. Do not include markdown or explanation text.
Respect these limits exactly:
- key_concepts: 1-10 items
- sub_queries: 2-5 items
- source_budgets: 1-6 items
- domain_keywords: 1-15 items
- dense_k: 2-20
- bm25_k: 0-12
- mmr_k: 1-15 and never greater than dense_k
- priority_weight: 0.2-3.0
If you have more ideas than the limit, keep only the highest-value items.
Produce the complete QueryPlan now.
"""
)


def _build_planner_user_prompt(query: str, course_id: str, mode: RetrievalMode) -> str:
    mode_notes = {
        RetrievalMode.ASK: (
            "MODE: ASK (explain/answer)\n"
            "Goal: Retrieve diverse, high-quality explanations and examples.\n"
            "Priority: Correctness and depth over breadth.\n"
            "expected_answer_format: structured_explanation or definition_then_example\n"
            "Populate quiz_config=null, summary_config=null."
        ),
        RetrievalMode.QUIZ: (
            "MODE: QUIZ (generate questions)\n"
            "Goal: Retrieve exam-style content, past questions, definitions, and worked examples.\n"
            "Priority: qna source is critical. Retrieve varied content for question variety.\n"
            "expected_answer_format: quiz_questions\n"
            "Populate quiz_config with appropriate settings. summary_config=null."
        ),
        RetrievalMode.SUMMARIZE: (
            "MODE: SUMMARIZE (topic summary)\n"
            "Goal: Retrieve broad coverage — definitions, explanations, examples, applications.\n"
            "Priority: Coverage over depth. All sources relevant.\n"
            "expected_answer_format: topic_summary\n"
            "Populate summary_config with appropriate settings. quiz_config=null."
        ),
    }
    return (
        f"STUDENT QUERY: {query!r}\n"
        f"COURSE ID: {course_id}\n\n"
        f"{mode_notes[mode]}\n\n"
        "Analyse the query and produce the complete retrieval plan."
    )


# ─────────────────────────────────────────────────────────────────────────────
# Gemini client helpers
# ─────────────────────────────────────────────────────────────────────────────
def _gemini_client() -> genai.Client:
    api_key = os.getenv("GEMINI_API_KEY", "").strip()

    print("ACTIVE GEMINI KEY:", api_key[:20] if api_key else "NONE")

    if not api_key:
        raise RuntimeError("GEMINI_API_KEY is not set.")

    return genai.Client(api_key=api_key)


def _embed(text: str) -> list[float]:
    client = _gemini_client()
    result = client.models.embed_content(
        model=EMBEDDING_MODEL,
        contents=text.strip() or " ",
        config=types.EmbedContentConfig(
            task_type="RETRIEVAL_QUERY",
            output_dimensionality=EMBEDDING_DIM,
        ),
    )
    return list(result.embeddings[0].values)


def _is_retryable_gemini_error(exc: Exception) -> bool:
    status_code = getattr(exc, "status_code", None)
    if status_code in {429, 500, 502, 503, 504}:
        return True
    message = str(exc).lower()
    return "client has been closed" in message or "temporarily unavailable" in message


def _generate_planner_content(
    *,
    contents: str,
    config: types.GenerateContentConfig,
):
    last_exc: Exception | None = None
    tried_models: set[str] = set()

    for model in [PLANNER_MODEL, PLANNER_FALLBACK_MODEL]:
        if not model:
            continue

        if model in tried_models:
            continue

        tried_models.add(model)

        try:
            client = _gemini_client()

            print("\n===== PLANNER DEBUG =====")
            print("MODEL:", model)
            print("KEY PREFIX:", os.getenv("GEMINI_API_KEY", "")[:20])
            print("=========================\n")

            response = client.models.generate_content(
                model=model,
                contents=contents,
                config=config,
            )

            print("✅ GEMINI CALL SUCCESS")

            return response

        except Exception as exc:
            print("\n===== GEMINI ERROR =====")
            print("MODEL:", model)
            print(type(exc).__name__)
            print(exc)
            print("========================\n")

            last_exc = exc

            if not _is_retryable_gemini_error(exc):
                raise

    if last_exc:
        raise last_exc

    raise RuntimeError("No Gemini planner model is configured.")


# ─────────────────────────────────────────────────────────────────────────────
# Step 1 — Planner Agent
# ─────────────────────────────────────────────────────────────────────────────

def run_planner(query: str, course_id: str, mode: RetrievalMode) -> QueryPlan:
    """Call the Gemini Planner Agent. Returns a structured QueryPlan."""
    user_prompt = (
        _build_planner_user_prompt(query, course_id, mode)
        + "\n\nReturn only valid JSON that can be parsed into this Pydantic model schema:\n"
        + json.dumps(QueryPlan.model_json_schema(), ensure_ascii=True)
    )
    print("\n===== PLANNER DEBUG =====")
    print("QUERY:", query)
    print("MODEL:", PLANNER_MODEL)
    print("=========================\n")
    response = _generate_planner_content(
        contents=user_prompt,
        config=types.GenerateContentConfig(
            system_instruction=_PLANNER_SYSTEM,
            response_mime_type="application/json",
            # Enterprise Agent Platform only:
            # response_schema=QueryPlan,
            temperature=0.2,
            max_output_tokens=4096,
        ),
    )
    parsed = getattr(response, "parsed", None)
    if isinstance(parsed, QueryPlan):
        return parsed
    return QueryPlan.model_validate_json(response.text)


# ─────────────────────────────────────────────────────────────────────────────
# Step 2 — Sub-query deduplication
# ─────────────────────────────────────────────────────────────────────────────

_STOPWORDS = {
    "a","an","the","is","in","on","of","to","for","and","or","with","that",
    "this","it","as","at","be","by","from","its","was","are","were","has",
    "have","had","not","but","can","will","just","do","did","so","if","we",
    "you","he","she","they","what","how","why","when","where","which","who",
}


def _tokenize(text: str) -> list[str]:
    tokens = re.findall(r"[a-zA-Z0-9_]{2,}", text.lower())
    return [t for t in tokens if t not in _STOPWORDS]


def _jaccard(a: str, b: str) -> float:
    sa, sb = set(_tokenize(a)), set(_tokenize(b))
    if not sa or not sb:
        return 0.0
    return len(sa & sb) / len(sa | sb)


def _deduplicate_sub_queries(sub_queries: list[SubQuery], threshold: float = 0.72) -> list[SubQuery]:
    kept: list[SubQuery] = []
    for sq in sub_queries:
        if all(_jaccard(sq.text, k.text) < threshold for k in kept):
            kept.append(sq)
        else:
            logger.debug("Dropped near-duplicate sub-query: %r", sq.text)
    return kept


# ─────────────────────────────────────────────────────────────────────────────
# Step 3 — Dense retrieval (Pinecone ANN)
# ─────────────────────────────────────────────────────────────────────────────

def _pinecone_index(index_name: str = PINECONE_INDEX_NAME):
    pc = Pinecone(api_key=PINECONE_API_KEY)
    return pc.Index(index_name)


def dense_retrieve(
    query_vec:       list[float],
    namespace:       str,
    top_k:           int,
    course_id:       str,
    index_name:      str = PINECONE_INDEX_NAME,
) -> list[dict]:
    """ANN search in Pinecone for one (query_vec, namespace) pair."""
    index = _pinecone_index(index_name)
    query_kwargs: dict[str, Any] = {
        "vector": query_vec,
        "top_k": top_k,
        "namespace": namespace,
        "include_metadata": True,
    }
    try:
        results = index.query(**query_kwargs)
        return [
            {"id": m.id, "score": float(m.score), "metadata": m.metadata or {}}
            for m in results.matches
        ]
    except Exception as exc:
        logger.warning("Dense retrieve failed (ns=%s): %s", namespace, exc)
        return []


# ─────────────────────────────────────────────────────────────────────────────
# Step 4 — BM25 sparse retrieval
# ─────────────────────────────────────────────────────────────────────────────

def _get_bm25_text(meta: dict, source_key: str) -> str:
    """Extract the most keyword-rich text for BM25 indexing."""
    if source_key == "qna":
        qs  = meta.get("questions", []) or []
        ans = meta.get("answers",   []) or []
        parts = ([qs] if isinstance(qs, str) else list(qs)) + \
                ([ans] if isinstance(ans, str) else list(ans))
        combined = " ".join(str(p) for p in parts)
        return combined or meta.get("raw_text", "")

    elif source_key == "image":
        return " ".join(filter(None, [
            meta.get("raw_text", ""),
            meta.get("gemini_summary", ""),
            meta.get("gemini_topic", ""),
            " ".join(meta.get("gemini_keywords", []) or []),
        ]))

    elif source_key == "handwritten":
        return " ".join(filter(None, [
            meta.get("transcript", meta.get("raw_text", "")),
            meta.get("topic", ""),
            meta.get("summary", ""),
        ]))

    elif source_key == "documents":
        return " ".join(filter(None, [
            meta.get("raw_text", meta.get("text_preview", "")),
            meta.get("section_title", ""),
            meta.get("keywords", ""),
        ]))

    # audio / youtube — less reliable for BM25, but use if requested
    return (
        meta.get("raw_text") or
        meta.get("text") or
        meta.get("transcript") or
        meta.get("text_preview") or
        ""
    )


def bm25_retrieve(
    query: str,
    corpus_hits: list[dict],
    top_k: int,
    source_key: str,
) -> list[dict]:
    """BM25 re-ranking over a dense candidate corpus."""
    if not corpus_hits or top_k == 0:
        return []
    texts = [_get_bm25_text(h["metadata"], source_key) for h in corpus_hits]
    tokenized_corpus = [_tokenize(t) for t in texts]
    tokenized_query  = _tokenize(query)
    if not tokenized_query:
        return corpus_hits[:top_k]
    bm25 = BM25Okapi(tokenized_corpus)
    scores = bm25.get_scores(tokenized_query)
    max_s = float(scores.max()) if scores.max() > 0 else 1.0
    normed = scores / max_s
    ranked = sorted(range(len(corpus_hits)), key=lambda i: normed[i], reverse=True)
    results = []
    for rank_idx, corpus_idx in enumerate(ranked[:top_k]):
        hit = dict(corpus_hits[corpus_idx])
        hit["bm25_score"] = float(normed[corpus_idx])
        hit["bm25_rank"]  = rank_idx + 1
        results.append(hit)
    return results


# ─────────────────────────────────────────────────────────────────────────────
# Step 5 — MMR diversity filtering
# ─────────────────────────────────────────────────────────────────────────────

def mmr_filter(
    candidates:  list[dict],
    k:           int,
    lambda_:     float = 0.6,
    source_key:  str   = "",
) -> list[dict]:
    """Maximal Marginal Relevance selection with source-aware redundancy heuristics."""
    if len(candidates) <= k:
        return candidates
    relevances = [c.get("score", 0.0) for c in candidates]
    selected: list[int] = [int(np.argmax(relevances))]
    remaining = [i for i in range(len(candidates)) if i != selected[0]]
    while len(selected) < k and remaining:
        best_i, best_mmr = -1, -float("inf")
        for i in remaining:
            rel = relevances[i]
            max_sim = 0.0
            for j in selected:
                mi = candidates[i].get("metadata", {})
                mj = candidates[j].get("metadata", {})
                same_file = (
                    mi.get("source_file", "") == mj.get("source_file", "") or
                    mi.get("file_name", "")   == mj.get("file_name", "")
                )
                idx_i = mi.get("chunk_index", mi.get("window_index", -99))
                idx_j = mj.get("chunk_index", mj.get("window_index", -99))
                adjacent = (
                    isinstance(idx_i, int) and
                    isinstance(idx_j, int) and
                    abs(idx_i - idx_j) <= 2
                )
                sim = 0.85 if (same_file and adjacent) else (0.5 if same_file else relevances[i] * relevances[j])
                max_sim = max(max_sim, sim)
            mmr_score = lambda_ * rel - (1 - lambda_) * max_sim
            if mmr_score > best_mmr:
                best_mmr, best_i = mmr_score, i
        if best_i >= 0:
            selected.append(best_i)
            remaining.remove(best_i)
    return [candidates[i] for i in selected]


# ─────────────────────────────────────────────────────────────────────────────
# Step 6 — Metadata-boosted Reciprocal Rank Fusion
# ─────────────────────────────────────────────────────────────────────────────

def _metadata_boost(meta: dict, source_key: str, high_value_signals: list[str]) -> float:
    """
    Small multiplicative boost based on metadata signals.
    Keeps source-aware ranking deterministic and local.
    """
    boost = 1.0
    signals_lower = [s.lower() for s in high_value_signals]

    if source_key == "qna":
        if meta.get("marks_hint") and int(meta.get("marks_hint", 0)) > 0:
            boost *= 1.12   # exam questions with explicit marks are high-value
        if meta.get("year_hint"):
            boost *= 1.05
        if meta.get("chunk_type") in ("single_qa", "multi_qa"):
            if any("exam" in s or "question" in s for s in signals_lower):
                boost *= 1.10

    elif source_key == "handwritten":
        if meta.get("has_equations") and any("equation" in s or "formula" in s for s in signals_lower):
            boost *= 1.15
        if meta.get("content_type") == "equation":
            boost *= 1.08
        if meta.get("confidence", 1.0) < 0.6:
            boost *= 0.85   # penalise low-confidence OCR

    elif source_key == "image":
        conf = float(meta.get("ocr_confidence", meta.get("mean_confidence", 80))) / 100
        if conf < 0.65:
            boost *= 0.80
        if meta.get("has_formula") and any("formula" in s or "equation" in s for s in signals_lower):
            boost *= 1.12

    elif source_key == "audio":
        if meta.get("strategy") == "concept_block":
            boost *= 1.08   # concept blocks are more focused than sliding windows
        avg_conf = float(meta.get("avg_confidence", 0.8))
        if avg_conf < 0.7:
            boost *= 0.90

    elif source_key == "documents":
        if meta.get("has_table") and any("table" in s or "comparison" in s for s in signals_lower):
            boost *= 1.10

    return boost


def reciprocal_rank_fusion(
    ranked_lists:       list[list[tuple[str, dict]]],
    weights:            list[float],
    source_keys:        list[str],
    high_value_signals: list[str],
    k: int = RRF_K,
) -> dict[str, tuple[float, dict]]:
    """RRF with metadata-aware boosting."""
    scores:     dict[str, float] = {}
    meta_store: dict[str, dict]  = {}
    sk_store:   dict[str, str]   = {}

    for ranked_list, weight, sk in zip(ranked_lists, weights, source_keys):
        for rank, (chunk_id, metadata) in enumerate(ranked_list, start=1):
            boost = _metadata_boost(metadata, sk, high_value_signals)
            scores[chunk_id] = scores.get(chunk_id, 0.0) + weight * boost / (k + rank)
            if chunk_id not in meta_store:
                meta_store[chunk_id] = metadata
                sk_store[chunk_id]   = sk

    return {cid: (scores[cid], meta_store[cid]) for cid in scores}


# ─────────────────────────────────────────────────────────────────────────────
# ─────────────────────────────────────────────────────────────────────────────

# Metadata inference helpers

def _infer_source_key(meta: dict) -> str:
    """Infer pipeline origin from metadata fingerprint."""
    if "video_id" in meta or "deep_link" in meta:
        return "youtube"
    if "ink_quality" in meta or "writing_style" in meta or "model_used" in meta:
        return "handwritten"
    if "strategy" in meta and meta.get("strategy") in {"sliding_window", "concept_block", "lecture_summary"}:
        return "audio"
    if "gemini_summary" in meta or "gemini_topic" in meta or "ocr_confidence" in meta:
        return "image"
    if meta.get("chunk_type") in {"single_qa", "multi_qa", "passage"} or "year_hint" in meta:
        return "qna"
    if "section_title" in meta or "has_table" in meta or "ingested_at" in meta:
        return "documents"
    return "documents"


def _parse_page_range(meta: dict) -> str:
    pr = meta.get("page_range")
    if isinstance(pr, list) and len(pr) == 2:
        return f"{pr[0]}–{pr[1]}"
    ps = meta.get("page_start")
    pe = meta.get("page_end")
    if ps is not None and pe is not None:
        return f"{int(ps)}–{int(pe)}" if ps != pe else str(int(ps))
    pn = meta.get("page_number")
    if pn is not None:
        return str(int(pn))
    return str(pr) if pr else ""


def _seconds_to_label(sec: float) -> str:
    total = int(sec)
    h, rem = divmod(total, 3600)
    m, s   = divmod(rem, 60)
    return f"{h:02d}:{m:02d}:{s:02d}" if h else f"{m:02d}:{s:02d}"


def _build_retrieved_chunk(
    chunk_id:          str,
    meta:              dict,
    namespace:         str,
    source_key:        str,
    rrf_score:         float,
    retrieval_methods: list[str],
) -> RetrievedChunk:
    text = (
        meta.get("raw_text") or meta.get("text") or
        meta.get("transcript") or meta.get("text_preview") or ""
    )
    keywords_raw = meta.get("keywords", meta.get("gemini_keywords", []))
    if isinstance(keywords_raw, str):
        keywords = [k.strip() for k in keywords_raw.split(",") if k.strip()]
    elif isinstance(keywords_raw, list):
        keywords = keywords_raw
    else:
        keywords = []

    chunk = RetrievedChunk(
        chunk_id          = chunk_id,
        source_key        = source_key,
        namespace         = namespace,
        score             = round(rrf_score, 4),
        rrf_score         = rrf_score,
        retrieval_methods = retrieval_methods,
        text              = text,
        source_file       = meta.get("source_file", meta.get("file_name", "")),
        course_id         = meta.get("course_id", ""),
        page_range        = _parse_page_range(meta),
        section_title     = meta.get("section_title", meta.get("section", "")),
        topic             = meta.get("topic", meta.get("topic_label", meta.get("gemini_topic", ""))),
        chunk_type        = meta.get("chunk_type", meta.get("strategy", meta.get("content_type", ""))),
        keywords          = keywords[:10],
    )

    if source_key == "qna":
        qs = meta.get("questions", [])
        an = meta.get("answers",   [])
        chunk.questions  = qs if isinstance(qs, list) else ([qs] if qs else [])
        chunk.answers    = an if isinstance(an, list) else ([an] if an else [])
        chunk.year_hint  = meta.get("year_hint")
        chunk.marks_hint = meta.get("marks_hint")
        chunk.difficulty = meta.get("difficulty_hint", "unknown")

    elif source_key == "image":
        signals = meta.get("gemini_content_signals", []) or []
        chunk.image_type    = meta.get("image_type", signals[0] if signals else "")
        chunk.image_summary = meta.get("gemini_summary", "")
        chunk.ocr_confidence = float(meta.get("ocr_confidence", meta.get("mean_confidence", 0)) or 0) / 100

    elif source_key == "audio":
        chunk.strategy     = meta.get("strategy", "")
        chunk.start_seconds = float(meta.get("start_seconds", 0.0))
        chunk.end_seconds   = float(meta.get("end_seconds",   0.0))
        chunk.start_label   = meta.get("start_label", _seconds_to_label(chunk.start_seconds))
        chunk.end_label     = meta.get("end_label",   _seconds_to_label(chunk.end_seconds))
        chunk.lecture_title = meta.get("lecture_title", "")
        chunk.professor     = meta.get("professor", "")
        chunk.week_number   = meta.get("week_number")

    elif source_key == "youtube":
        chunk.video_id      = meta.get("video_id", "")
        chunk.video_title   = meta.get("video_title", "")
        chunk.channel_author = meta.get("author", "")
        chunk.deep_link     = meta.get("deep_link", "")
        chunk.chapter_title = meta.get("chapter_title", "")
        chunk.start_label   = meta.get("start_label", "")
        chunk.end_label     = meta.get("end_label",   "")
        chunk.text          = meta.get("raw_text", chunk.text)

    elif source_key == "handwritten":
        chunk.ink_quality   = meta.get("ink_quality", "")
        chunk.writing_style = meta.get("writing_style", "")
        chunk.content_type  = meta.get("content_type", "")
        chunk.has_equations = bool(meta.get("has_equations", False))
        chunk.has_diagrams  = bool(meta.get("has_diagrams", False))
        chunk.model_used    = meta.get("model_used", "")
        chunk.text = (
            meta.get("structured_markdown") or
            meta.get("transcript") or chunk.text
        )

    elif source_key == "documents":
        chunk.has_table = bool(meta.get("has_table", False))
        chunk.has_image = bool(meta.get("has_image", False))
        chunk.has_list  = bool(meta.get("has_list",  False))

    return chunk


# ─────────────────────────────────────────────────────────────────────────────
# Main retrieve() function
# ─────────────────────────────────────────────────────────────────────────────

def retrieve(
    query:      str,
    course_id:  str,
    mode:       RetrievalMode = RetrievalMode.ASK,
    top_k:      int   = 8,
    index_name: str | None = None,
    verbose:    bool  = False,
) -> RetrievalResult:
    """
    Full agentic RAG retrieval pipeline.

    Parameters
    ----------
    query      : Student's natural language question or topic.
    course_id  : Selects the course-specific Pinecone index.
    mode       : RetrievalMode.ASK | QUIZ | SUMMARIZE
    top_k      : Final number of chunks returned.
    index_name : Optional Pinecone index override. Defaults to the course index.
    verbose    : Print step-by-step progress.

    Returns
    -------
    RetrievalResult with citation-ready chunks and a complete answer prompt.
    """
    t_start = time.perf_counter()
    target_index_name = index_name or get_course_index_name(course_id)

    # ── 1. Planner ─────────────────────────────────────────────────────────
    if verbose:
        print(f"\n{'='*65}")
        print(f"[1/5] Planner Agent | mode={mode.value} | query={query!r}")
    plan = run_planner(query, course_id, mode)
    plan.sub_queries = _deduplicate_sub_queries(plan.sub_queries)

    if verbose:
        print(f"      Intent    : {plan.query_intent[:90]}")
        print(f"      Category  : {plan.query_category}  ({plan.complexity_level})")
        print(f"      Sub-queries ({len(plan.sub_queries)}):")
        for sq in plan.sub_queries:
            print(f"        [{sq.facet}] {sq.text!r}")
        print(f"      Sources   : {[b.source_key for b in plan.source_budgets]}")

    # ── 2. Embed sub-queries ───────────────────────────────────────────────
    if verbose:
        print(f"[2/5] Embedding {len(plan.sub_queries)} sub-queries …")
    query_vecs: dict[str, list[float]] = {sq.text: _embed(sq.text) for sq in plan.sub_queries}

    # ── 3. Multi-retrieval fan-out ─────────────────────────────────────────
    if verbose:
        print(f"[3/5] Retrieving from {len(plan.source_budgets)} source(s) …")

    rrf_inputs:       list[tuple[list[tuple[str, dict]], float, str]] = []
    chunk_methods:    dict[str, set[str]]  = {}
    chunk_meta_store: dict[str, dict]      = {}
    chunk_namespace:  dict[str, str]       = {}
    chunk_sourcekey:  dict[str, str]       = {}

    for budget in plan.source_budgets:
        sk = budget.source_key
        if sk not in SOURCE_NAMESPACES:
            logger.warning("Unknown source key: %r — skipping", sk)
            continue
        ns = SOURCE_NAMESPACES[sk]

        for sq in plan.sub_queries:
            q_vec = query_vecs[sq.text]
            fetch_k = budget.dense_k * BM25_CORPUS_MULTIPLIER if budget.bm25_k > 0 else budget.dense_k

            # Dense retrieval
            dense_hits = dense_retrieve(
                query_vec     = q_vec,
                namespace     = ns,
                top_k         = min(fetch_k, 40),
                course_id     = course_id,
                index_name    = target_index_name,
            )

            for h in dense_hits:
                cid = h["id"]
                chunk_meta_store[cid] = h["metadata"]
                chunk_namespace[cid]  = ns
                chunk_sourcekey[cid]  = sk
                chunk_methods.setdefault(cid, set()).add("dense")

            # MMR filtering
            if budget.use_mmr and len(dense_hits) > budget.mmr_k:
                before = len(dense_hits)
                dense_hits = mmr_filter(
                    candidates = dense_hits,
                    k          = budget.mmr_k,
                    lambda_    = budget.mmr_lambda,
                    source_key = sk,
                )
                if verbose:
                    print(f"        MMR [{sk}]: {before} → {len(dense_hits)}")
                for h in dense_hits:
                    chunk_methods.setdefault(h["id"], set()).add("mmr")

            dense_ranked: list[tuple[str, dict]] = [
                (h["id"], h["metadata"]) for h in dense_hits[:budget.dense_k]
            ]
            if dense_ranked:
                rrf_inputs.append((dense_ranked, budget.priority_weight, sk))

            # BM25
            if budget.bm25_k > 0 and dense_hits:
                bm25_hits = bm25_retrieve(
                    query        = sq.text,
                    corpus_hits  = dense_hits,
                    top_k        = budget.bm25_k,
                    source_key   = sk,
                )
                for h in bm25_hits:
                    cid = h["id"]
                    chunk_methods.setdefault(cid, set()).add("bm25")
                    chunk_meta_store[cid] = h["metadata"]
                    chunk_namespace[cid]  = ns
                    chunk_sourcekey[cid]  = sk

                bm25_weight_mult = {
                    "qna": 1.4, "image": 1.2, "documents": 1.2,
                    "handwritten": 1.1, "audio": 0.9, "youtube": 0.8,
                }.get(sk, 1.0)
                bm25_ranked: list[tuple[str, dict]] = [
                    (h["id"], h["metadata"]) for h in bm25_hits
                ]
                if bm25_ranked:
                    rrf_inputs.append((bm25_ranked, budget.priority_weight * bm25_weight_mult, sk))

        if verbose:
            print(f"      [{sk}] → {len(chunk_meta_store)} unique candidates so far")

    # ── 4. Metadata-boosted RRF Fusion ─────────────────────────────────────
    if verbose:
        print(f"[4/5] RRF fusion over {len(rrf_inputs)} ranked lists …")

    if not rrf_inputs:
        logger.warning("No retrieval results — returning empty result.")
        return RetrievalResult(
            query=query, mode=mode, plan=plan, chunks=[],
            total_candidates=0,
            latency_ms=(time.perf_counter() - t_start) * 1000,
        )

    fused = reciprocal_rank_fusion(
        ranked_lists       = [rl for rl, _, _ in rrf_inputs],
        weights            = [w  for _, w, _ in rrf_inputs],
        source_keys        = [sk for _, _, sk in rrf_inputs],
        high_value_signals = plan.high_value_signals,
    )
    total_candidates = len(fused)
    sorted_fused = sorted(fused.items(), key=lambda x: x[1][0], reverse=True)

    # ── 5. Score-based selection ────────────────────────────────────────────
    pool_size = min(top_k, total_candidates)
    final_pool = sorted_fused[:pool_size]

    if verbose:
        print(f"[5/5] Score-based selection ({pool_size} candidates → {top_k} final) …")

    # ── Assemble final chunks ──────────────────────────────────────────────
    final_chunks: list[RetrievedChunk] = []

    for cid, (rrf_score, meta) in final_pool:
        ns = chunk_namespace.get(cid, "")
        sk = chunk_sourcekey.get(cid, _infer_source_key(meta))

        chunk = _build_retrieved_chunk(
            chunk_id          = cid,
            meta              = meta,
            namespace         = ns,
            source_key        = sk,
            rrf_score         = rrf_score,
            retrieval_methods = sorted(chunk_methods.get(cid, {"dense"})),
        )
        chunk.score = round(rrf_score, 4)
        final_chunks.append(chunk)

    final_chunks.sort(key=lambda c: c.score, reverse=True)
    final_chunks = final_chunks[:top_k]

    source_breakdown: dict[str, int] = {}
    for c in final_chunks:
        source_breakdown[c.source_key] = source_breakdown.get(c.source_key, 0) + 1

    latency_ms = (time.perf_counter() - t_start) * 1000

    if verbose:
        print(f"\n✅ Done in {latency_ms:.0f} ms — {total_candidates} candidates → {len(final_chunks)} chunks")
        print(f"   Source breakdown: {source_breakdown}")
        for i, c in enumerate(final_chunks, 1):
            print(f"   [{i}] {c.score:.3f}  [{c.source_key}]  {c.citation_label[:55]}")

    return RetrievalResult(
        query            = query,
        mode             = mode,
        plan             = plan,
        chunks           = final_chunks,
        total_candidates = total_candidates,
        latency_ms       = latency_ms,
        source_breakdown = source_breakdown,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Async wrapper
# ─────────────────────────────────────────────────────────────────────────────

async def aretrieve(
    query:      str,
    course_id:  str,
    mode:       RetrievalMode = RetrievalMode.ASK,
    top_k:      int  = 8,
    index_name: str | None = None,
    verbose:    bool = False,
) -> RetrievalResult:
    """Async wrapper — runs sync pipeline in a thread pool."""
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(
        None,
        lambda: retrieve(
            query=query,
            course_id=course_id,
            mode=mode,
            top_k=top_k,
            index_name=index_name,
            verbose=verbose,
        ),
    )


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s  %(levelname)-8s  %(message)s",
        datefmt="%H:%M:%S",
    )

    parser = argparse.ArgumentParser(
        description="University AI Course Assistant — Retrieval Pipeline"
    )
    parser.add_argument("query",       help="Student question or topic")
    parser.add_argument("--course-id", required=True)
    parser.add_argument("--mode",      choices=["ask","quiz","summarize"], default="ask")
    parser.add_argument("--top-k",     type=int, default=8)
    parser.add_argument("--verbose",   action="store_true", default=True)
    args = parser.parse_args()

    result = retrieve(
        query      = args.query,
        course_id  = args.course_id,
        mode       = RetrievalMode(args.mode),
        top_k      = args.top_k,
        verbose    = args.verbose,
    )

    print("\n" + "=" * 70)
    print(f"QUERY          : {result.query}")
    print(f"MODE           : {result.mode.value}")
    print(f"CATEGORY       : {result.plan.query_category}")
    print(f"INTENT         : {result.plan.query_intent}")
    print(f"KEY CONCEPTS   : {', '.join(result.plan.key_concepts)}")
    print(f"FORMAT         : {result.plan.expected_answer_format} ({result.plan.expected_answer_length})")
    print(f"SOURCES USED   : {result.source_breakdown}")
    print(f"CANDIDATES     : {result.total_candidates}  →  {len(result.chunks)} final")
    print(f"LATENCY        : {result.latency_ms:.0f} ms")
    print("=" * 70)
    print("\nSUB-QUERIES:")
    for sq in result.plan.sub_queries:
        print(f"  [{sq.facet}] {sq.text}")
    print("\nCONTEXT FOR ANSWER GENERATOR:")
    print(result.to_context_string())



