"""add email otp

Revision ID: 1262b5bb5897
Revises: 8e9d51c76d05
Create Date: 2026-06-21 01:57:38.380467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '1262b5bb5897'
down_revision: Union[str, Sequence[str], None] = '8e9d51c76d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###