"""add chat history

Revision ID: 95e7fca2d2d4
Revises: 1262b5bb5897
Create Date: 2026-06-21 23:29:28.090073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '95e7fca2d2d4'
down_revision: Union[str, Sequence[str], None] = '1262b5bb5897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###